if (self.CavalryLogger) { CavalryLogger.start_js(["AecFm83"]); }

__d("LWICometManagementRootContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="3118002828323789"}),null);
__d("LWICometManagementRootContentQuery$Parameters",["LWICometManagementRootContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("LWICometManagementRootContentQuery_facebookRelayOperation"),metadata:{},name:"LWICometManagementRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PagesCometAdminWhatsappUpsellDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7246946661997467"}),null);
__d("PagesCometAdminWhatsappUpsellDialogQuery$Parameters",["PagesCometAdminWhatsappUpsellDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PagesCometAdminWhatsappUpsellDialogQuery_facebookRelayOperation"),metadata:{},name:"PagesCometAdminWhatsappUpsellDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("getFirstAssetOfType",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){return a.find(function(a){return a.type===b})}f["default"]=a}),66);
__d("EventCometMutatePaidEventOnboardingPromptDialogResource",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a=c("JSResourceForInteraction")("EventCometMutatePaidEventOnboardingPromptDialog.react").__setRef("EventCometMutatePaidEventOnboardingPromptDialogResource");b=a;g["default"]=b}),98);
__d("AdsLWICoBManagementDialog.entrypoint",["JSResourceForInteraction","LWICometManagementRootContentQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{managementRootQueryRef:{parameters:b("LWICometManagementRootContentQuery$Parameters"),variables:{boostID:a.boostID,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("AdsLWICoBManagementDialog.react").__setRef("AdsLWICoBManagementDialog.entrypoint")};g["default"]=a}),98);
__d("PagesCometAdminLiveTabContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b={isLeftNavNuxVisible:!1,pageID:"",setIsLeftNavNuxVisible:function(){}};c=a.createContext(b);g["default"]=c}),98);
__d("PagesCometAdminWhatsappUpsellDialog.entrypoint",["JSResourceForInteraction","PagesCometAdminWhatsappUpsellDialogQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{dialogQueryReference:{parameters:c("PagesCometAdminWhatsappUpsellDialogQuery$Parameters"),variables:{pageID:a.pageID}}}}},root:c("JSResourceForInteraction")("PagesCometAdminWhatsappUpsellDialog.react").__setRef("PagesCometAdminWhatsappUpsellDialog.entrypoint")};g["default"]=a}),98);
__d("CometPageAdminCreateWhatsAppAdsInterstitialUpsellQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5216171528410405"}),null);
__d("PagesCometAdminPageSelectorPopoverRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4509489979149915"}),null);
__d("PagesCometAdminWhatsAppPostingUpsellDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4485929768141879"}),null);